name: Публикация версии сайта

on:
  release:
    types: [published]

jobs:
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Скопировать репозиторий
      uses: actions/checkout@v4

    - name: Создать папку с версией релиза
      run: |
        mkdir -p "version-${{ github.event.release.tag_name }}"
        cp -r *.html ru/ en/ "version-${{ github.event.release.tag_name }}"/

    - name: Опубликовать сайт
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./version-${{ github.event.release.tag_name }}
