name: Публикация релиза на GitHub Pages

on:
  release:
    types: [created]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Скопировать репозиторий
      uses: actions/checkout@v3

    - name: Создать папку с версией релиза
      run: |
        mkdir -p "v${{ github.event.release.tag_name }}"
        cp -r * "v${{ github.event.release.tag_name }}"

    - name: Опубликовать сайт
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./v${{ github.event.release.tag_name }}
